/** Real product screenshots served from /landing/*.png */
export const SCREENSHOT_CATEGORIES = [
  { id: 'sales', label: 'Sales' },
  { id: 'engage', label: 'Engage' },
  { id: 'automate', label: 'Automate' },
  { id: 'manage', label: 'Manage' },
  { id: 'settings', label: 'Settings' },
]

export const LANDING_SCREENSHOTS = [
  {
    id: 'pipeline',
    src: '/landing/pipeline.png',
    title: 'Pipeline',
    caption: 'Deals by pipeline status — list and board; stage columns reflect each opportunity’s current status',
    category: 'sales',
  },
  {
    id: 'deals-pipeline',
    src: '/landing/deals-pipeline.png',
    title: 'Deals Pipeline',
    caption: 'Visual kanban board from Qualification through Won with deal value and revenue totals',
    category: 'sales',
  },
  {
    id: 'lead-distribution',
    src: '/landing/lead-distribution.png',
    title: 'Lead distribution',
    caption: 'Fairly assign unassigned leads to your calling team using round-robin rotation',
    category: 'sales',
  },
  {
    id: 'leads',
    src: '/landing/leads.png',
    title: 'Leads',
    caption: 'Full lifecycle from raw prospect to qualified opportunity — every touchpoint in one place',
    category: 'sales',
  },
  {
    id: 'opportunities',
    src: '/landing/opportunities.png',
    title: 'Opportunities',
    caption: 'Pipeline deals — leads marked as opportunities with pipeline status front and center',
    category: 'sales',
  },
  {
    id: 'deals-detail-tasks',
    src: '/landing/deals-detail-tasks.png',
    title: 'Deal workspace',
    caption: 'Activity, notes, tasks, payments, quotations, and invoices on every deal',
    category: 'sales',
  },
  {
    id: 'deals-detail-quotations',
    src: '/landing/deals-detail-quotations.png',
    title: 'Deal quotations',
    caption: 'Create and convert quotations directly from deal records',
    category: 'sales',
  },
  {
    id: 'dashboard',
    src: '/landing/dashboard.png',
    title: 'Dashboard',
    caption: 'Home screen — overview of all key metrics, tasks due today, and pipeline health',
    category: 'sales',
  },
  {
    id: 'email-inbox',
    src: '/landing/email-inbox.png',
    title: 'Email',
    caption: 'Send, receive, and track emails without leaving the CRM — full inbox inside the app',
    category: 'engage',
  },
  {
    id: 'email-thread',
    src: '/landing/email-thread.png',
    title: 'Email threads',
    caption: 'Reply, view lead, and create emails from conversation threads linked to contacts',
    category: 'engage',
  },
  {
    id: 'my-task-list',
    src: '/landing/my-task-list.png',
    title: 'My Task',
    caption: 'You have 34 tasks ongoing. Stay focused and complete them on time.',
    category: 'engage',
  },
  {
    id: 'my-task-calendar',
    src: '/landing/my-task-calendar.png',
    title: 'Task calendar',
    caption: 'Calendar view for follow-ups, due dates, and lead-linked tasks',
    category: 'engage',
  },
  {
    id: 'activities',
    src: '/landing/activities.png',
    title: 'Activities',
    caption: 'Everything that happened — calls, emails, meetings, notes — in a filterable timeline',
    category: 'engage',
  },
  {
    id: 'calls-meetings',
    src: '/landing/calls-meetings.png',
    title: 'Calls & meetings',
    caption: 'Log, record, and analyse every phone call and meeting — full call intelligence',
    category: 'engage',
  },
  {
    id: 'templates',
    src: '/landing/templates.png',
    title: 'Templates',
    caption: 'Create and manage email templates with merge tags, delivery safeguards, and send history',
    category: 'engage',
  },
  {
    id: 'workflow-editor',
    src: '/landing/workflow-editor.png',
    title: 'Automation',
    caption: 'No-code workflow rules — trigger actions automatically when conditions are met',
    category: 'automate',
  },
  {
    id: 'campaigns',
    src: '/landing/campaigns.png',
    title: 'Campaigns',
    caption: 'Coordinate multi-step outreach to segments — assign leads and track campaign progress',
    category: 'automate',
  },
  {
    id: 'webforms',
    src: '/landing/webforms.png',
    title: 'Web forms & lead capture',
    caption: 'Embed forms on your website — leads flow straight into the CRM automatically',
    category: 'automate',
  },
  {
    id: 'edit-quotation',
    src: '/landing/edit-quotation.png',
    title: 'Quotations',
    caption: 'Structured quotes with templates, totals, and PDF-ready layouts',
    category: 'manage',
  },
  {
    id: 'documents',
    src: '/landing/documents.png',
    title: 'Documents',
    caption: 'Central file store — contracts, presentations, NDAs — linked to leads or deals',
    category: 'manage',
  },
  {
    id: 'team-roles',
    src: '/landing/team-roles.png',
    title: 'Team & roles',
    caption: 'Invite people, assign roles, control what each role can see and do',
    category: 'settings',
  },
  {
    id: 'workspace-settings',
    src: '/landing/workspace-settings.png',
    title: 'Workspace settings',
    caption: 'Manage workspaces, then use Company information for legal name, GSTIN, logo, and invoice details',
    category: 'settings',
  },
  {
    id: 'integrations-api',
    src: '/landing/integrations-api.png',
    title: 'Integrations & API',
    caption: 'Connect your CRM to every other tool your company uses',
    category: 'settings',
  },
]

export const HERO_SCREENSHOT = '/landing/pipeline.png'
