// Screen name constants + the web menu route each screen maps to (permission gating).
// Web routes come from client/src/components/layout/navConfig.js + appRoutes.js.

export const ROUTES = {
  // Tabs
  TABS: 'Tabs',
  TAB_DASHBOARD: 'Dashboard',
  TAB_LEADS: 'Leads',
  TAB_OPPORTUNITIES: 'Opportunities',
  TAB_ACTIVITIES: 'Activities',
  TAB_CALL_LOGS: 'CallLogs',
  TAB_MORE: 'More',
  // Pushed
  LEAD_DETAIL: 'LeadDetail',
  ADD_LEAD: 'AddLead',
  EDIT_LEAD: 'EditLead',
  OPPORTUNITY_DETAIL: 'OpportunityDetail',
  TASKS: 'Tasks',
  CALLS: 'Calls',
  MEETINGS: 'Meetings',
  MEETING_DETAIL: 'MeetingDetail',
  MEETING_FORM: 'MeetingForm',
  DOCUMENTS: 'Documents',
  NOTIFICATIONS: 'Notifications',
  CALENDAR: 'Calendar',
  ATTENDANCE: 'Attendance',
  LEAVE: 'Leave',
  ACTIVITY_LEGACY: 'Activity',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  CHANGE_PASSWORD: 'ChangePassword',
  SETTINGS_APPEARANCE: 'Appearance',
  SETTINGS_SECURITY: 'Security',
  TEAM_LIST: 'TeamList',
  TEAM_MEMBER_DETAIL: 'TeamMemberDetail',
  INVITATIONS: 'Invitations',
  ROLES: 'Roles',
  DEALS: 'Deals',
  DEAL_DETAIL: 'DealDetail',
  SALES_DOCS: 'SalesDocs',
  SALES_DOC_DETAIL: 'SalesDocDetail',
  SEARCH: 'Search',
  PIPELINE: 'Pipeline',
  CAMPAIGNS: 'Campaigns',
  CAMPAIGN_DETAIL: 'CampaignDetail',
  REPORTS: 'Reports',
  REPORT_DETAIL: 'ReportDetail',
  COPILOT: 'Copilot',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
};

// Screen → web menu route (null = always allowed). Checked with useCan().
export const ROUTE_PERMISSIONS = {
  [ROUTES.TAB_DASHBOARD]: null,
  [ROUTES.TAB_LEADS]: '/leads',
  [ROUTES.TAB_OPPORTUNITIES]: '/opportunities',
  [ROUTES.TAB_ACTIVITIES]: '/activities',
  [ROUTES.TAB_CALL_LOGS]: '/calls',
  [ROUTES.TAB_MORE]: null,
  [ROUTES.LEAD_DETAIL]: '/leads',
  [ROUTES.ADD_LEAD]: '/leads',
  [ROUTES.EDIT_LEAD]: '/leads',
  [ROUTES.OPPORTUNITY_DETAIL]: '/opportunities',
  [ROUTES.TASKS]: '/tasks',
  [ROUTES.CALLS]: '/calls',
  [ROUTES.MEETINGS]: '/meetings',
  [ROUTES.MEETING_DETAIL]: '/meetings',
  [ROUTES.MEETING_FORM]: '/meetings',
  [ROUTES.DOCUMENTS]: '/documents',
  [ROUTES.NOTIFICATIONS]: null,
  [ROUTES.CALENDAR]: '/calendar',
  [ROUTES.ATTENDANCE]: '/attendance',
  [ROUTES.LEAVE]: '/leave',
  [ROUTES.ACTIVITY_LEGACY]: '/activities',
  [ROUTES.PROFILE]: null,
  [ROUTES.EDIT_PROFILE]: null,
  [ROUTES.CHANGE_PASSWORD]: null,
  [ROUTES.SETTINGS_APPEARANCE]: null,
  [ROUTES.SETTINGS_SECURITY]: null,
  [ROUTES.TEAM_LIST]: '/team',
  [ROUTES.TEAM_MEMBER_DETAIL]: '/team',
  [ROUTES.INVITATIONS]: '/team',
  [ROUTES.ROLES]: '/team',
  [ROUTES.DEALS]: '/deals',
  [ROUTES.DEAL_DETAIL]: '/deals',
  [ROUTES.SALES_DOCS]: '/quotations',
  [ROUTES.SALES_DOC_DETAIL]: '/quotations',
  [ROUTES.SEARCH]: null,
  [ROUTES.PIPELINE]: '/pipeline',
  [ROUTES.CAMPAIGNS]: '/campaigns',
  [ROUTES.CAMPAIGN_DETAIL]: '/campaigns',
  [ROUTES.REPORTS]: '/reports',
  [ROUTES.REPORT_DETAIL]: '/reports',
  [ROUTES.COPILOT]: '/copilot',
  // No dedicated web menu key for notification settings — gate behind the
  // admin-only workspace settings area (matches the server's isCompanyAdmin check).
  [ROUTES.NOTIFICATION_SETTINGS]: '/workspace',
};
