import { DataTypes } from 'sequelize'
import { sequelize } from '../config/db.js'

export const Quotation = sequelize.define(
  'Quotation',
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    workspaceId: { type: DataTypes.UUID, allowNull: false, field: 'workspace_id' },
    companyId: { type: DataTypes.UUID, allowNull: false, field: 'company_id' },
    quotationTemplateId: { type: DataTypes.UUID, allowNull: true, field: 'quotation_template_id' },
    leadId: { type: DataTypes.UUID, allowNull: false, field: 'lead_id' },
    dealId: { type: DataTypes.UUID, allowNull: true, field: 'deal_id' },
    ownerUserId: { type: DataTypes.UUID, allowNull: true, field: 'owner_user_id' },
    quotationNumber: { type: DataTypes.STRING(64), allowNull: false, field: 'quotation_number' },
    issueDate: { type: DataTypes.DATEONLY, allowNull: false, field: 'issue_date' },
    expiryDate: { type: DataTypes.DATEONLY, allowNull: true, field: 'expiry_date' },
    reference: { type: DataTypes.STRING(120), allowNull: true },
    purchaseOrderRef: { type: DataTypes.STRING(120), allowNull: true, field: 'purchase_order_ref' },
    customerSnapshot: { type: DataTypes.JSON, allowNull: false, field: 'customer_snapshot' },
    subtotal: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
    discountTotal: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0, field: 'discount_total' },
    shipping: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
    adjustment: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
    grandTotal: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0, field: 'grand_total' },
    taxBreakdown: { type: DataTypes.JSON, allowNull: true, field: 'tax_breakdown' },
    currency: { type: DataTypes.STRING(3), allowNull: false, defaultValue: 'USD' },
    status: { type: DataTypes.STRING(24), allowNull: false, defaultValue: 'draft' },
    sentAt: { type: DataTypes.DATE, allowNull: true, field: 'sent_at' },
    viewedAt: { type: DataTypes.DATE, allowNull: true, field: 'viewed_at' },
    convertedInvoiceId: { type: DataTypes.UUID, allowNull: true, field: 'converted_invoice_id' },
    pdfStorageKey: { type: DataTypes.STRING(512), allowNull: true, field: 'pdf_storage_key' },
    termsSnapshot: { type: DataTypes.TEXT, allowNull: true, field: 'terms_snapshot' },
    notes: { type: DataTypes.TEXT, allowNull: true },
    layoutPreset: { type: DataTypes.TINYINT.UNSIGNED, allowNull: false, defaultValue: 1, field: 'layout_preset' },
    documentTheme: { type: DataTypes.JSON, allowNull: true, field: 'document_theme' },
    preparedByName: { type: DataTypes.STRING(160), allowNull: true, field: 'prepared_by_name' },
    approvalStatus: { type: DataTypes.STRING(24), allowNull: true, field: 'approval_status' },
  },
  { tableName: 'quotations' },
)
