import { DataTypes } from 'sequelize'
import { sequelize } from '../config/db.js'

export const WebFormField = sequelize.define(
  'WebFormField',
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    formId: { type: DataTypes.UUID, allowNull: false, field: 'form_id' },
    type: {
      type: DataTypes.ENUM(
        'text',
        'email',
        'phone',
        'number',
        'textarea',
        'select',
        'multiselect',
        'checkbox',
        'radio',
        'date',
        'file',
        'heading',
        'paragraph',
        'divider',
        'hidden',
      ),
      allowNull: false,
    },
    label: { type: DataTypes.STRING(255), allowNull: true },
    placeholder: { type: DataTypes.STRING(255), allowNull: true },
    helpText: { type: DataTypes.STRING(255), allowNull: true, field: 'help_text' },
    defaultValue: { type: DataTypes.STRING(500), allowNull: true, field: 'default_value' },
    isRequired: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'is_required' },
    isHidden: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'is_hidden' },
    order: { type: DataTypes.INTEGER, allowNull: false },
    width: { type: DataTypes.ENUM('full', 'half'), allowNull: false, defaultValue: 'full' },
    options: { type: DataTypes.JSON, allowNull: true },
    showCountryCode: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'show_country_code' },
    defaultCountryCode: { type: DataTypes.STRING(8), allowNull: false, defaultValue: '+91', field: 'default_country_code' },
    minLength: { type: DataTypes.INTEGER, allowNull: true, field: 'min_length' },
    maxLength: { type: DataTypes.INTEGER, allowNull: true, field: 'max_length' },
    minValue: { type: DataTypes.FLOAT, allowNull: true, field: 'min_value' },
    maxValue: { type: DataTypes.FLOAT, allowNull: true, field: 'max_value' },
    pattern: { type: DataTypes.STRING(255), allowNull: true },
    patternError: { type: DataTypes.STRING(255), allowNull: true, field: 'pattern_error' },
    crmField: { type: DataTypes.STRING(120), allowNull: true, field: 'crm_field' },
  },
  { tableName: 'web_form_fields', timestamps: true },
)
