import { DataTypes } from 'sequelize'
import { sequelize } from '../config/db.js'

export const WorkspaceBillingProfile = sequelize.define(
  'WorkspaceBillingProfile',
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    workspaceId: {
      type: DataTypes.UUID,
      allowNull: false,
      unique: true,
      field: 'workspace_id',
    },
    companyId: { type: DataTypes.UUID, allowNull: false, field: 'company_id' },
    legalName: { type: DataTypes.STRING(240), allowNull: true, field: 'legal_name' },
    logoUrl: { type: DataTypes.STRING(512), allowNull: true, field: 'logo_url' },
    taxIdLabel: { type: DataTypes.STRING(64), allowNull: true, field: 'tax_id_label' },
    taxIdValue: { type: DataTypes.STRING(64), allowNull: true, field: 'tax_id_value' },
    addressLine1: { type: DataTypes.STRING(255), allowNull: true, field: 'address_line1' },
    addressLine2: { type: DataTypes.STRING(255), allowNull: true, field: 'address_line2' },
    city: { type: DataTypes.STRING(120), allowNull: true },
    state: { type: DataTypes.STRING(120), allowNull: true },
    postalCode: { type: DataTypes.STRING(32), allowNull: true, field: 'postal_code' },
    country: { type: DataTypes.STRING(2), allowNull: true },
    phone: { type: DataTypes.STRING(64), allowNull: true },
    email: { type: DataTypes.STRING(190), allowNull: true },
    website: { type: DataTypes.STRING(255), allowNull: true },
    bankName: { type: DataTypes.STRING(160), allowNull: true, field: 'bank_name' },
    bankAccountHolderName: {
      type: DataTypes.STRING(240),
      allowNull: true,
      field: 'bank_account_holder_name',
    },
    bankBranch: { type: DataTypes.STRING(255), allowNull: true, field: 'bank_branch' },
    micrCode: { type: DataTypes.STRING(16), allowNull: true, field: 'micr_code' },
    bankAccountType: { type: DataTypes.STRING(32), allowNull: true, field: 'bank_account_type' },
    bankAccountNumber: { type: DataTypes.STRING(64), allowNull: true, field: 'bank_account_number' },
    bankIfsc: { type: DataTypes.STRING(32), allowNull: true, field: 'bank_ifsc' },
    bankSwift: { type: DataTypes.STRING(32), allowNull: true, field: 'bank_swift' },
    upiId: { type: DataTypes.STRING(120), allowNull: true, field: 'upi_id' },
    paymentLinkUrl: { type: DataTypes.STRING(512), allowNull: true, field: 'payment_link_url' },
    paymentInstructions: { type: DataTypes.TEXT, allowNull: true, field: 'payment_instructions' },
    signatureImageUrl: { type: DataTypes.STRING(512), allowNull: true, field: 'signature_image_url' },
    stampImageUrl: { type: DataTypes.STRING(512), allowNull: true, field: 'stamp_image_url' },
    quotationPrefix: { type: DataTypes.STRING(32), allowNull: false, defaultValue: 'QT', field: 'quotation_prefix' },
    quotationNextSeq: {
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
      defaultValue: 1001,
      field: 'quotation_next_seq',
    },
    quotationNumberFormat: {
      type: DataTypes.STRING(32),
      allowNull: false,
      defaultValue: 'PREFIX/DDMMYYYY/SEQ',
      field: 'quotation_number_format',
    },
    invoicePrefix: { type: DataTypes.STRING(32), allowNull: false, defaultValue: 'INV', field: 'invoice_prefix' },
    invoiceNextSeq: {
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
      defaultValue: 1001,
      field: 'invoice_next_seq',
    },
    invoiceNumberFormat: {
      type: DataTypes.STRING(32),
      allowNull: false,
      defaultValue: 'PREFIX/DDMMYYYY/SEQ',
      field: 'invoice_number_format',
    },
  },
  { tableName: 'workspace_billing_profiles' },
)
