import { DataTypes } from 'sequelize'
import { sequelize } from '../config/db.js'

export const Invoice = sequelize.define(
  'Invoice',
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    workspaceId: { type: DataTypes.UUID, allowNull: false, field: 'workspace_id' },
    companyId: { type: DataTypes.UUID, allowNull: false, field: 'company_id' },
    invoiceTemplateId: { type: DataTypes.UUID, allowNull: true, field: 'invoice_template_id' },
    quotationId: { type: DataTypes.UUID, allowNull: true, field: 'quotation_id' },
    leadId: { type: DataTypes.UUID, allowNull: false, field: 'lead_id' },
    dealId: { type: DataTypes.UUID, allowNull: true, field: 'deal_id' },
    ownerUserId: { type: DataTypes.UUID, allowNull: true, field: 'owner_user_id' },
    invoiceNumber: { type: DataTypes.STRING(64), allowNull: false, field: 'invoice_number' },
    issueDate: { type: DataTypes.DATEONLY, allowNull: false, field: 'issue_date' },
    dueDate: { type: DataTypes.DATEONLY, allowNull: true, field: 'due_date' },
    purchaseOrderRef: { type: DataTypes.STRING(120), allowNull: true, field: 'purchase_order_ref' },
    reference: { type: DataTypes.STRING(120), allowNull: true },
    customerSnapshot: { type: DataTypes.JSON, allowNull: false, field: 'customer_snapshot' },
    subtotal: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
    discountTotal: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0, field: 'discount_total' },
    roundOff: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0, field: 'round_off' },
    grandTotal: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0, field: 'grand_total' },
    taxFinancial: { type: DataTypes.JSON, allowNull: true, field: 'tax_financial' },
    currency: { type: DataTypes.STRING(3), allowNull: false, defaultValue: 'USD' },
    status: { type: DataTypes.STRING(24), allowNull: false, defaultValue: 'draft' },
    paymentBlockSnapshot: { type: DataTypes.JSON, allowNull: true, field: 'payment_block_snapshot' },
    termsSnapshot: { type: DataTypes.TEXT, allowNull: true, field: 'terms_snapshot' },
    notes: { type: DataTypes.TEXT, allowNull: true },
    layoutPreset: { type: DataTypes.TINYINT.UNSIGNED, allowNull: false, defaultValue: 1, field: 'layout_preset' },
    documentTheme: { type: DataTypes.JSON, allowNull: true, field: 'document_theme' },
    showBankDetails: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'show_bank_details' },
    amountPaid: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0, field: 'amount_paid' },
    pdfStorageKey: { type: DataTypes.STRING(512), allowNull: true, field: 'pdf_storage_key' },
  },
  { tableName: 'invoices' },
)
