import { DataTypes } from 'sequelize'
import { sequelize } from '../config/db.js'

export const QuotationTemplate = sequelize.define(
  'QuotationTemplate',
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    workspaceId: { type: DataTypes.UUID, allowNull: false, field: 'workspace_id' },
    companyId: { type: DataTypes.UUID, allowNull: false, field: 'company_id' },
    name: { type: DataTypes.STRING(200), allowNull: false },
    code: { type: DataTypes.STRING(64), allowNull: false },
    category: { type: DataTypes.STRING(64), allowNull: true },
    defaultCurrency: { type: DataTypes.STRING(3), allowNull: false, defaultValue: 'USD', field: 'default_currency' },
    language: { type: DataTypes.STRING(16), allowNull: false, defaultValue: 'en' },
    status: { type: DataTypes.STRING(16), allowNull: false, defaultValue: 'active' },
    defaultTaxType: { type: DataTypes.STRING(16), allowNull: false, defaultValue: 'none', field: 'default_tax_type' },
    defaultValidityDays: {
      type: DataTypes.SMALLINT,
      allowNull: false,
      defaultValue: 30,
      field: 'default_validity_days',
    },
    defaultPaymentTerms: { type: DataTypes.TEXT, allowNull: true, field: 'default_payment_terms' },
    watermark: { type: DataTypes.STRING(16), allowNull: false, defaultValue: 'none' },
    themeColor: { type: DataTypes.STRING(16), allowNull: true, field: 'theme_color' },
    fontFamily: { type: DataTypes.STRING(120), allowNull: true, field: 'font_family' },
    layoutPreset: { type: DataTypes.TINYINT.UNSIGNED, allowNull: false, defaultValue: 1, field: 'layout_preset' },
    sectionSettings: { type: DataTypes.JSON, allowNull: true, field: 'section_settings' },
    logoOverrideUrl: { type: DataTypes.STRING(512), allowNull: true, field: 'logo_override_url' },
    accentOverride: { type: DataTypes.STRING(16), allowNull: true, field: 'accent_override' },
    defaultTermsBlocks: { type: DataTypes.JSON, allowNull: true, field: 'default_terms_blocks' },
    defaultNotes: { type: DataTypes.TEXT, allowNull: true, field: 'default_notes' },
    showSku: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'show_sku' },
    showHsn: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'show_hsn' },
    showDiscount: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'show_discount' },
    showTaxPerLine: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'show_tax_per_line' },
    approvalRules: { type: DataTypes.JSON, allowNull: true, field: 'approval_rules' },
  },
  { tableName: 'quotation_templates' },
)
