import { DataTypes } from 'sequelize'
import { sequelize } from '../config/db.js'

export const WebForm = sequelize.define(
  'WebForm',
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    name: { type: DataTypes.STRING(255), allowNull: false },
    description: { type: DataTypes.STRING(512), allowNull: true },
    publicToken: { type: DataTypes.STRING(128), allowNull: false, unique: true, field: 'public_token' },
    status: { type: DataTypes.ENUM('draft', 'active', 'paused', 'archived'), allowNull: false, defaultValue: 'draft' },
    formTitle: { type: DataTypes.STRING(255), allowNull: true, field: 'form_title' },
    formSubtitle: { type: DataTypes.STRING(500), allowNull: true, field: 'form_subtitle' },
    submitButtonText: { type: DataTypes.STRING(100), allowNull: false, defaultValue: 'Submit', field: 'submit_button_text' },
    primaryColor: { type: DataTypes.STRING(16), allowNull: false, defaultValue: '#3b73f5', field: 'primary_color' },
    textColor: { type: DataTypes.STRING(16), allowNull: false, defaultValue: '#0f1117', field: 'text_color' },
    backgroundColor: { type: DataTypes.STRING(16), allowNull: false, defaultValue: '#ffffff', field: 'background_color' },
    formWidth: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 760, field: 'form_width' },
    fontFamily: { type: DataTypes.STRING(100), allowNull: false, defaultValue: 'Plus Jakarta Sans', field: 'font_family' },
    borderRadius: { type: DataTypes.ENUM('none', 'sm', 'md', 'lg'), allowNull: false, defaultValue: 'md', field: 'border_radius' },
    thankyouType: { type: DataTypes.ENUM('message', 'redirect'), allowNull: false, defaultValue: 'message', field: 'thankyou_type' },
    thankyouMessage: { type: DataTypes.TEXT, allowNull: false, defaultValue: 'Thank you! We will be in touch soon.', field: 'thankyou_message' },
    thankyouRedirectUrl: { type: DataTypes.STRING(1024), allowNull: true, field: 'thankyou_redirect_url' },
    displayType: { type: DataTypes.ENUM('inline', 'popup', 'slidein'), allowNull: false, defaultValue: 'inline', field: 'display_type' },
    popupTrigger: { type: DataTypes.ENUM('exit_intent', 'time_delay', 'scroll_depth', 'button_click'), allowNull: false, defaultValue: 'time_delay', field: 'popup_trigger' },
    popupDelay: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 5, field: 'popup_delay' },
    popupScrollPct: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 50, field: 'popup_scroll_pct' },
    popupButtonSelector: { type: DataTypes.STRING(200), allowNull: true, field: 'popup_button_selector' },
    popupOverlay: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'popup_overlay' },
    popupPosition: { type: DataTypes.ENUM('center', 'bottom-right', 'bottom-left', 'bottom-center'), allowNull: false, defaultValue: 'center', field: 'popup_position' },
    defaultStatus: { type: DataTypes.STRING(64), allowNull: false, defaultValue: 'new', field: 'default_status' },
    defaultSource: { type: DataTypes.STRING(64), allowNull: false, defaultValue: 'web_form', field: 'default_source' },
    defaultAssignedTo: { type: DataTypes.UUID, allowNull: true, field: 'default_assigned_to' },
    autoAssign: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'auto_assign' },
    notifyOnSubmission: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'notify_on_submission' },
    notificationRecipients: { type: DataTypes.JSON, allowNull: false, defaultValue: [], field: 'notification_recipients' },
    notificationSubject: { type: DataTypes.STRING(255), allowNull: true, field: 'notification_subject' },
    sendConfirmationEmail: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'send_confirmation_email' },
    confirmationSubject: { type: DataTypes.STRING(255), allowNull: true, field: 'confirmation_subject' },
    confirmationBody: { type: DataTypes.TEXT, allowNull: true, field: 'confirmation_body' },
    recaptchaEnabled: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'recaptcha_enabled' },
    recaptchaSiteKey: { type: DataTypes.STRING(255), allowNull: true, field: 'recaptcha_site_key' },
    recaptchaSecretKey: { type: DataTypes.STRING(255), allowNull: true, field: 'recaptcha_secret_key' },
    honeypotEnabled: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true, field: 'honeypot_enabled' },
    totalSubmissions: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0, field: 'total_submissions' },
    totalViews: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0, field: 'total_views' },
    allowedDomains: { type: DataTypes.JSON, allowNull: false, defaultValue: [], field: 'allowed_domains' },
    autoTags: { type: DataTypes.JSON, allowNull: false, defaultValue: [], field: 'auto_tags' },
    workspaceId: { type: DataTypes.UUID, allowNull: false, field: 'workspace_id' },
    createdBy: { type: DataTypes.UUID, allowNull: true, field: 'created_by' },
  },
  {
    tableName: 'web_forms',
    timestamps: true,
    paranoid: true,
  },
)
