/** Whitelisted lead list filter fields for advanced query builder. */
export const LEAD_FILTER_FIELDS = {
  title: { type: 'text', label: 'Title' },
  contactName: { type: 'text', label: 'Contact name' },
  company: { type: 'text', label: 'Company' },
  email: { type: 'text', label: 'Email' },
  phone: { type: 'text', label: 'Phone' },
  status: {
    type: 'enum',
    label: 'Status',
    values: ['new', 'contacted', 'qualified', 'proposal', 'won', 'lost', 'junk'],
  },
  source: {
    type: 'enum',
    label: 'Source',
    values: ['web_form', 'manual', 'csv_import', 'api', 'referral', 'campaign', 'linkedin', 'cold_email', 'other'],
  },
  assignedTo: { type: 'uuid', label: 'Owner' },
  ownerUserId: { type: 'uuid', label: 'Record owner' },
  score: { type: 'number', label: 'Health score' },
  value: { type: 'number', label: 'Deal value' },
  opportunityStage: { type: 'text', label: 'Stage' },
  city: { type: 'text', label: 'City' },
  state: { type: 'text', label: 'State' },
  country: { type: 'text', label: 'Country' },
  createdAt: { type: 'date', label: 'Created date' },
  updatedAt: { type: 'date', label: 'Last modified' },
  closingDate: { type: 'date', label: 'Closing date' },
  isOpportunity: { type: 'boolean', label: 'Is opportunity' },
}
