import { NOTIFICATION_EVENT_TYPES } from './notificationEventTypes.js'

/** Always sent, never suppressible by role/user preferences or quiet hours. */
export const MANDATORY_EVENT_TYPES = new Set([
  NOTIFICATION_EVENT_TYPES.EMAIL_VERIFICATION,
  NOTIFICATION_EVENT_TYPES.PASSWORD_RESET,
  NOTIFICATION_EVENT_TYPES.USER_INVITATION,
  NOTIFICATION_EVENT_TYPES.SECURITY_NEW_DEVICE_LOGIN,
  NOTIFICATION_EVENT_TYPES.SECURITY_PASSWORD_CHANGED,
  NOTIFICATION_EVENT_TYPES.SECURITY_EMAIL_CHANGED,
])

export function isMandatoryEvent(eventType) {
  return MANDATORY_EVENT_TYPES.has(eventType)
}
